// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/ui/Accordion.vue')['default']
    ActiveDevice: typeof import('./src/components/device/ActiveDevice.vue')['default']
    CreateProductForm: typeof import('./src/components/product/CreateProductForm.vue')['default']
    DataTable: typeof import('./src/components/ui/DataTable.vue')['default']
    Errors: typeof import('./src/components/ui/Errors.vue')['default']
    FormWizard: typeof import('./src/components/device/FormWizard.vue')['default']
    InformationDevice: typeof import('./src/components/device/InformationDevice.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    Otp: typeof import('./src/components/ui/Otp.vue')['default']
    RButton: typeof import('./src/components/ui/RButton.vue')['default']
    RInput: typeof import('./src/components/ui/RInput.vue')['default']
    RModal: typeof import('./src/components/ui/RModal.vue')['default']
    RNavigationDrawer: typeof import('./src/components/ui/RNavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RSelect: typeof import('./src/components/ui/RSelect.vue')['default']
    RToggle: typeof import('./src/components/ui/RToggle.vue')['default']
    SensorsDevice: typeof import('./src/components/device/SensorsDevice.vue')['default']
  }
}
